#!/bin/bash
# Copyright (C) CNES - All Rights Reserved
# This file is subject to the terms and conditions defined in
# file 'LICENSE.md', which is part of this source code package.
#
# Author:      Peter KETTIG <peter.kettig@cnes.fr>
# Project:     Weighted Average Synthesis Processor (WASP)
# Filename:    WASP
# Created on:  4 Sep 2018

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Throw error when sourced (This would delete the PYTHON-variables):
if [[ ${BASH_SOURCE[0]} != $0 ]]; then
	printf "ERROR: Script %s must not run sourced\n" "${BASH_SOURCE[0]}"
	return 1
fi

# Unset Environment variables if necessary:
if [[ ! -z "${PYTHONPATH}" ]]; then
	unset PYTHONPATH
fi

if [[ ! -z "${PYTHONHOME}" ]]; then
	unset PYTHONHOME
fi

# Check availability:
if [ ! -f $DIR/python3 ] || [ ! -f $DIR/WASP.py ]; then
	echo "Cannot find WASP executable."; return 1
fi

# Forward all other arguments:
$DIR/python3 $DIR/WASP.py $@
